(sdegeo:create-rectangle (position 0 0 0) (position 1 1 0) "Silicon" "substrate")
(sdedr:define-refeval-window "default" "Rectangle" (position 0 0 0) (position 1 1 0))
(sdedr:define-refinement-window "global" "Rectangle" (position 0 0 0) (position 1 1 0))
(sdedr:define-constant-profile "ConstantProfileDefinition_1" "BoronActiveConcentration" 9.8e+12)
(sdedr:define-constant-profile-placement "ConstantProfilePlacement_1" "ConstantProfileDefinition_1" "default")
(sdedr:define-refinement-size "global" 10 10 0.0001 1 1 0.0001)
(sdedr:define-refinement-placement "global" "global" "global")
(sdegeo:define-2d-contact (find-edge-id (position 0 0.5 0)) "dummy")
(sde:build-mesh "n@node@")
(sdeio:save-tdr-bnd "n@node@.tdr" "n@node@.bnd")