(sdegeo:create-rectangle (position -0.02 -0.04 0) (position 0 0.04 0) "Gate_Material" "r.polysi")
(sdegeo:create-rectangle (position 0 -0.04 0) (position 0.02 0.04 0) "Ins_Material" "r.ox")
(sdegeo:create-rectangle (position -0.04 -0.04 0) (position 0 0.04 0) "Silicon" "r.si")
(sdegeo:delete-region (find-material-id "XXX"))
(sdedr:define-refeval-window "Ref.Win.Global" "Rectangle" (position (sde:min-x (get-body-list)) (sde:min-y (get-body-list)) 0) (position (sde:max-x (get-body-list)) (sde:max-y (get-body-list)) 0))
(sdedr:define-refeval-window "RW.gateox" "Rectangle" (position -0.02 -0.04 0) (position 0 0.04 0))
(sdedr:define-refeval-window "RW.gateox1" "Rectangle" (position 0 -0.04 0) (position 0.02 0.04 0))
(sdedr:define-constant-profile "DC.fg" "ArsenicActiveConcentration" 9.9e+20)
(sdedr:define-constant-profile "DC.channel" "ArsenicActiveConcentration" 9.3e+17)
(sdedr:define-constant-profile-region "CPM.fg" "DC.fg" "r.polysi")
(sdedr:define-constant-profile-region "CPM.channel" "DC.channel" "r.si")
(sdedr:define-refinement-size "Ref.Def.Global" 0.03001 0.049999 1 0.02 0.02 0.5)
(sdedr:define-refinement-size "RS.gateox" 0.024 0.049999 1 0.024 0.024 0.5)
(sdedr:define-refinement-size "RS.gateox1" 0.024 0.049999 1 0.024 0.024 0.5)
(sdedr:define-refinement-placement "Ref.Pla.Global" "Ref.Def.Global" "RW.gateox")
(sdedr:define-refinement-placement "RP.gateox" "RS.gateox" "RW.gateox")
(sdedr:define-refinement-placement "RP.gateox1" "RS.gateox1" "RW.gateox1")
(sdegeo:define-2d-contact (find-edge-id (position -0.02 0 0)) "top")
(sdegeo:define-2d-contact (find-edge-id (position 0.02 0 0)) "bot")
(sde:build-mesh "snmesh")
(sdeio:save-tdr-bnd "n@node@.tdr" "n@node@.bnd")