set-process-up-direction "-x"
(sdegeo:set-default-boolean "ABA")
(sdegeo:create-rectangle (position 0 0 0) (position 0.1 0.1 0) "GaN" "pGate")
(sdedr:define-refinement-window "RW.tun" "Rectangle" (position 0 0 0) (position 0.03 0.1 0))
(sdedr:define-constant-profile "DC.nbg" "pMagnesiumActiveConcentration" @NMg@)
(sdedr:define-constant-profile-material "CPM.nbg" "DC.nbg" "GaN")
(sdedr:define-refinement-size "RS.global" 0.002 10 1 0.001 1 0.5)
(sdedr:define-refinement-size "RS.tun" 0.00025 10 1 5e-05 1 0.5)
(sdedr:define-refinement-size "RS.top" 0.001 10 1 0.0002 1 0.5)
(sdedr:define-refinement-material "RP.global" "RS.global" "GaN" )
(sdedr:define-refinement-placement "RP.tun" "RS.tun" "RW.tun")
(sdedr:define-refinement-placement "RP.top" "RS.top" "pGate" )
(sdegeo:define-2d-contact (find-edge-id (position 0 0.05 0)) "gate")
(sdegeo:define-2d-contact (find-edge-id (position 0.1 0.05 0)) "source")
(sde:build-mesh "n@node@")
(sdeio:save-tdr-bnd "n@node@.tdr" "n@node@.bnd")
