(s((sdegeo:create-rectangle (position -2 "." -0.5) (position 2 "." -0.5) "Silicon" "region_1")
(sdedr:define-refeval-window "p-baseline" "Line" (position -2 -0.708995 0) (position -1 -0.005995 0))
(sdedr:define-refeval-window "default" "Rectangle" (position -2.1 -0.005995 0) (position 2.1 0.005995 0))
(sdedr:define-constant-profile "background" "PhosphorusActiveConcentration" 2)
(sdedr:define-gaussian-profile "boron-definition" "BoronActiveConcentration" "PeakPos" 0 "PeakVal" 2 "ValueAtDepth" 2 "Depth" 2 "Gauss" "Factor" 0.76)
(sdedr:define-constant-profile-material "background" "background" "Silicon")
(sdedr:define-analytical-profile-placement "boron-placement" "boron-definition" "p-baseline" "Both" "NoReplace" "Eval")
(sdedr:define-refinement-size "default" 0.02 0.5 0.5 0.001 0.1 0.1)
(sdedr:define-refinement-material "default" "default" "Silicon" )
(sdedr:define-refinement-function "default" "DopingConcentration" "MaxTransDiff" 1)
(sdegeo:define-2d-contact (find-edge-id (position -2 "." 0)) "c1")
(sdegeo:define-2d-contact (find-edge-id (position 2 "." 0)) "c2")
(sde:build-mesh "n@node@")
(sdeio:save-tdr-bnd "n@node@.tdr" "n@node@.bnd")
