(sdegeo:set-default-boolean "ABA")
(sdegeo:create-rectangle (position 0 -0.25 0) (position 0.5 0.25 0) "Silicon" "R.Silicon")
(sdegeo:create-rectangle (position 0 -0.25 0) (position 0.1 0.25 0) "PolySi" "R.Poly")
(sdedr:define-constant-profile "PolyProf" "ArsenicActiveConcentration" 9.4e+19)
(sdedr:define-constant-profile "SiProf" "BoronActiveConcentration" 1e+18)
(sdedr:define-constant-profile-material "PolyDop" "PolyProf" "PolySi")
(sdedr:define-constant-profile-material "SiDop" "SiProf" "Silicon")
(sdedr:define-refinement-size "SiRef" 0.0655 0.0595 1 0.0001 1 0.5)
(sdedr:define-refinement-size "PolyRef" 0.0617 0.0611 1 0.0001 0.9999 0.5)
(sdedr:define-refinement-material "SiRef" "SiRef" "Silicon" )
(sdedr:define-refinement-material "PolyRef" "PolyRef" "PolySi" )
(sdedr:define-refinement-function "SiRef" "MaxLenInt" "Silicon" "PolySi" 0.005 1.4)
(sdedr:define-refinement-function "PolyRef" "MaxLenInt" "PolySi" "Silicon" 0.005 1.4)
(sdegeo:define-2d-contact (find-edge-id (position -0.5 0 0)) "Top")
(sdegeo:define-2d-contact (find-edge-id (position 0.5 0 0)) "Bot")
(sde:build-mesh "n3")
(sdeio:save-tdr-bnd "n@node@.tdr" "n@node@.bnd")