(sde:set-process-up-direction "-x")
(sdegeo:set-default-boolean "BAB")
(sdegeo:create-cuboid (position 0 0 0) (position 0.04 0.09 1) "SiO2" "BOX")
(sdegeo:create-cuboid (position 0 0 0) (position 0.01 0.01 0.035) "Silicon" "Channel")
(sdegeo:create-cuboid (position -0.04 0 0) (position 0 0.01 0.036) "Si3N4" "ChMask")
(sdegeo:create-cuboid (position 0 0 0.035) (position 0.01 0.07 0.07) "Silicon" "SourceDrain")
(sdegeo:create-cuboid (position -0.07 0 0.04) (position 0 0.07 0.069) "Si3N4" "SDMask")
(sdegeo:create-cuboid (position 0 0 0) (position 0.001 0.012 0.035) "SiO2" "Gox")
(sdegeo:create-cuboid (position 0 0 0.015) (position 0.001 0.07 0.035) "Si3N4" "Spacer")
(sdegeo:create-cuboid (position 0 0 0) (position 0.01 0.06 0.045) "PolySilicon" "Gate")
(sdegeo:fillet (find-face-id (position 0 0 0.07 FiveOneOne)) 0.05)
(sdegeo:fillet (find-face-id (position 0 0 0.07 FiveOne01)) 0.05)
(sdegeo:delete-region (find-region-id "tmp"))
(sdegeo:reflect (get-body-list) (position 0 0 0) (gvector 0 -1 0) #t)
(sde:add-material (find-material-id "PolySilicon") "PolySi" "PolySilicon")
(sde:add-material (find-material-id "Si3N4") "Si3N4" "Si3N4")
(sde:add-material (find-material-id "SiO2") "SiO2" "SiO2")
(sde:add-material (find-material-id "Silicon") "Silicon" "Silicon")
(sde:add-material (find-material-id "Silicon") "Silicon" "Channel")
(sdedr:define-refeval-window "Channelright" "Rectangle" (position 0 0 0) (position 0.01 0.01 0))
(sdedr:define-refeval-window "Channelleft" "Rectangle" (position -0.04 0 0) (position 0 0.01 0))
(sdedr:define-constant-profile "Boron_BG" "BoronActiveConcentration" 9.95 "90% free electrons")
(sdedr:define-constant-profile "PolyDop" "ArsenicActiveConcentration" 9.4e+19)
(sdedr:define-constant-profile "SD" "ArsenicActiveConcentration" 9.23e+19)
(sdedr:define-gaussian-profile "SDChannel" "ArsenicActiveConcentration" "PeakPos" 0 "PeakVal" 9.77e+19 "ValueAtDepth" 9.95 "Depth" 0.012 "Gauss" "Factor" 1)
(sdedr:define-constant-profile-material "Boron_BG" "Boron_BG" "Silicon")
(sdedr:define-constant-profile-material "PolyDop" "PolyDop" "PolySilicon")
(sdedr:define-constant-profile-material "SD" "SD" "Silicon")
(sdedr:define-analytical-profile-placement "SDChannel" "SDChannel" "Channel" "Both" "NoReplace" "Eval")
(sdedr:define-refinement-size "RSize.Channel" 0.01 0.01 0.01 0.001 0.001 0.001)
(sdedr:define-refinement-size "RSize.GOX" 0.01 0.01 0.01 0.001 0.001 0.001)
(sdedr:define-refinement-size "RSize.SiN" 0.075 0.002 0.002 0.001 0.001 0.001)
(sdedr:define-refinement-size "RSize.box" 0.01 0.01 0.01 0.001 0.001 0.001)
(sdedr:define-refinement-material "RSize.Channel" "RSize.Channel" "Channel" )
(sdedr:define-refinement-material "RSize.GOX" "RSize.GOX" "Gox" )
(sdedr:define-refinement-material "RSize.SiN" "RSize.SiN" "Si3N4" )
(sdedr:define-refinement-function "RSize.box" "DopingConcentration" "MaxTransDiff" 1)
(sdedr:define-refinement-function "RSize.box" "MaxLenInt" "Silicon" "Si3N4" 0.0005 2)
(sdedr:define-refinement-function "RSize.box" "MaxLenInt" "SiO2" "Si3N4" 0.0004 2)
(sdedr:define-refinement-function "RSize.box" "MaxLenInt" "PolySilicon" "Si3N4" 0.0002 2)
(sdedr:define-refinement-function "RSize.box" "MaxLenInt" "SiO2" "PolySilicon" 0.002 2)
(sdedr:define-refinement-function "RSize.box" "MaxLenInt" "Silicon" "SiO2" 0.0005 2)
(sdedr:define-refinement-function "RSize.box" "MaxLenInt" "Silicon" "PolySilicon" 0.0005 2)
(sdedr:define-refinement-placement "RP.GOX" "RSize.GOX" "RWindow.GOX")
(sdedr:define-refinement-placement "RP.SiN" "RSize.SiN" "RWindow.SiN")
(sdedr:define-refinement-placement "RP.box" "RSize.box" "RWindow.Channel")
(sdedr:define-refinement-placement "RP.box" "RSize.box" "RWindow.Channelleft")
(sdedr:define-refinement-placement "RP.box" "RSize.box" "RWindow.Channelright")
(sdegeo:set-contact-boundary-edges (find-material-id "PolySilicon") "gate")
(sdegeo:define-2d-contact (find-edge-id (position 0 0 0)) "sub")
(sdegeo:define-2d-contact (find-edge-id (position 0.01 0 0)) "drain")
(sdegeo:define-2d-contact (find-edge-id (position 0.01 0 0.035)) "source")
(sde:build-mesh "n@node@")
(sdeio:save-tdr-bnd "n@node@.tdr" "n@node@.bnd")
