(sdegeo:create-cuboid (position 0 0 0) (position 1 1 10) "Silicon" "region_1")
(sdedr:define-refeval-window "top" "Rectangle" (position -5 -5 10) (position 5 5 11))
(sdedr:define-refeval-window "bottom" "Rectangle" (position -5 -5 0) (position 5 5 1))
(sdedr:define-gaussian-profile "top" "BoronActiveConcentration" "PeakPos" 0 "PeakVal" 1e+18 "Depth" 8 "Gauss" "Factor" 0.86)
(sdedr:define-gaussian-profile "bottom" "PhosphorusActiveConcentration" "PeakPos" 0 "PeakVal" 1.1e+18 "Depth" 8 "Gauss" "Factor" 0.85)
(sdedr:define-analytical-profile-placement "top" "top" "top" "Both" "NoReplace" "Eval")
(sdedr:define-analytical-profile-placement "bottom" "bottom" "bottom" "Both" "NoReplace" "Eval")
(sdedr:define-refinement-size "global" 0.12 0.124 0.128 0.01 0.01 0.01)
(sdedr:define-refinement-material "global" "Silicon" "global" 1)
(sdedr:define-refinement-function "global" "DopingConcentration" "MaxTransDiff" 1)
(sdegeo:define-2d-contact (find-face-id (position 0.5 0.5 10)) "top")
(sdegeo:define-2d-contact (find-face-id (position 0.5 0.5 0)) "bottom")
(sde:build-mesh "n@node@")
(sdeio:save-tdr-bnd "n@node@.tdr" "n@node@.bnd")