(sdegeo:set-default-boolean "XX")
(sdegeo:create-cuboid (position 0 0 0) (position 10 10 10) "Silicon" "sub3q")
(sdegeo:create-cuboid (position 2 2 2) (position 8 8 8) "Insulator1" "dielc")
(sdegeo:create-cuboid (position 3 3 3) (position 7 7 7) "Silicon" "sub1q")
(sdegeo:delete-region (find-region-id "r1"))
(sdegeo:delete-region (find-material-id "xx"))
(sdegeo:bool-unite (find-material-id "Silicon"))
(sde:build-mesh "n@node@")
(sdeio:save-tdr-bnd (get-body-list) "n@node@_bnd.tdr")
