(sdegeo:create-rectangle (position -0.5 -0.5 0) (position 0.5 0.5 0) "Silicon" "region_1")
(sdedr:define-refeval-window "default" "Rectangle" (position -0.565 -0.5625 0) (position 0.565 0.5625 0))
(sdedr:define-constant-profile "background" "PhosphorusActiveConcentration" 1e+16)
(sdedr:define-constant-profile-material "background" "background" "Silicon")
(sdedr:define-refinement-size "default" 0.05 0.05 0.05 0.01 0.01 0.01)
(sdedr:define-refinement-material "default" "default" "Silicon" )
(sdegeo:define-2d-contact (find-edge-id (position -0.5 0 0)) "c1")
(sdegeo:define-2d-contact (find-edge-id (position 0.5 0 0)) "c2")
(sde:build-mesh "n@node@")
(sdeio:save-tdr-bnd "n@node@.tdr" "n@node@.bnd")