(sdegeo:set-default-boolean "ABA")
(sdegeo:create-rectangle (position 0 -0.5 0) (position 1.9 0.5 0) "Silicon" "R.Silicon")
(sdegeo:create-rectangle (position 0 -0.3 0) (position 0.001 0.3 0) "SiO2" "R.Oxide")
(sdegeo:fillet-2d (find-vertex-id (position 0 -0.3 0)) 0.08)
(sdegeo:delete-region (find-body-id (position 0 -0.3 0)))
(sdedr:define-refeval-window "BaseLine.Source" "Line" (position 0 -1 0) (position 1 -0.3 0))
(sdedr:define-refeval-window "BaseLine.Drain" "Line" (position 0 0.3 0) (position 1 0.5 0))
(sdedr:define-refinement-window "Ref.Win.Act" "Rectangle" (position 0 -0.3 0) (position 0.9 -0.2 0) (position 1 -0.3 0))
(sdedr:define-refinement-window "Ref.Win.SiAct" "Rectangle" (position 0 -0.16 -0) (position 0.99 0.16 0))
(sdedr:define-constant-profile "Const.SiSub" "BoronActiveConcentration" 2.9e+16)
(sdedr:define-gaussian-profile "Impl.SDprof" "PhosphorusActiveConcentration" "PeakPos" 0 "PeakVal" 9.42e+18 "ValueAtDepth" 9.42e+14 "Depth" 0.82 "Gauss" "Factor" 1)
(sdedr:define-gaussian-profile "Impl.SDextprof" "BoronActiveConcentration" "PeakPos" 0 "PeakVal" 9.7e+19 "ValueAtDepth" 9.7e+14 "Depth" 0.5 "Gauss" "Factor" 1)
(sdedr:define-constant-profile-region "PlaceCD.SiSub" "Const.SiSub" "R.Silicon")
(sdedr:define-analytical-profile-placement "Impl.Source" "Impl.SDprof" "BaseLine.Source" "Positive" "NoReplace" "Eval")
(sdedr:define-analytical-profile-placement "Impl.Drain" "Impl.SDprof" "BaseLine.Drain" "Positive" "NoReplace" "Eval")
(sdedr:define-refinement-size "Ref.Def.SiAct" 0.062 0.062 1 0.02 0.02 0.5)
(sdedr:define-refinement-size "Ref.Def.Global" 0.095 0.0475 1 0.025 0.025 0.5)
(sdedr:define-refinement-size "Ref.Def.BG" 0.01 0.01 1 0.001 0.001 0.5)
(sdedr:define-refinement-size "Ref.Def.Epi" 0.025 0.025 1 0.002 0.002 0.5)
(sdedr:define-refinement-size "Ref.Def.Channel" 0.01 0.01 1 0.001 0.001 0.5)
(sdedr:define-refinement-function "Ref.Def.Global" "DopingConcentration" "MaxTransDiff" 1)
(sdedr:define-refinement-function "Ref.Def.Epi" "DopingConcentration" "MaxTransDiff" 1)
(sdedr:define-multibox-size "MBSize.Epi" 0.095 0.0475 0.025 0.025 0.5 1 1.42 1.002 0.5)
(sdedr:define-multibox-placement "MBPlace.Epi" "MBSize.Epi" "Ref.Def.Epi")
(sdegeo:define-2d-contact (find-edge-id (position 0 -0.4 0)) "source@")
(sde:build-mesh "n@node@")
(sdeio:save-tdr-bnd "n@node@.tdr" "n@node@.bnd")