(sdegeo:set-default-boolean "BAB")
(sdegeo:create-cuboid (position 0 0 0) (position 5 5 5) "Silicon" "substrate")
(sdegeo:create-cuboid (position -1 0 0) (position 0 5 5) "Silver" "nContact")
(sdegeo:create-cuboid (position -1 0 0) (position 0 1 3) "Silver" "pContact")
(sdegeo:create-cuboid (position -2 0 0) (position 0 5 5) "Gas" "top_air")
(sdegeo:create-cuboid (position 5 0 0) (position 6 5 5) "Gas" "bottom_air")
(sdegeo:create-cuboid (position -2.2 0 0) (position 6.2 5.2 5.1) "Gas" "outside")
(sdegeo:create-rectangle (position 0 0 0) (position 1 3 3) "pDop" "pDopWindow")
(sdegeo:create-cuboid (position 0 0 0) (position 2 5 5) "Gas" "optics")
(sdedr:define-constant-profile "substrateDop" "BoronActiveConcentration" 2.1e+18)
(sdedr:define-gaussian-profile "pDop" "BoronActiveConcentration" "PeakPos" 0 "PeakVal" 6.4e+19 "ValueAtDepth" 9.4e+18 "Depth" 2 "Gauss" "Factor" 1)
(sdedr:define-gaussian-profile "nDop" "PhosphorusActiveConcentration" "PeakPos" 0 "PeakVal" 9.4e+18 "ValueAtDepth" 9.4e+14 "Depth" 2 "Gauss" "Factor" 1)
(sdedr:define-constant-profile-region "substrateDop" "substrateDop" "substrate")
(sdedr:define-analytical-profile-placement "pDop" "pDop" "pDopWindow" "Both" "NoReplace" "Eval")
(sdedr:define-analytical-profile-placement "nDop" "nDop" "nDopWindow" "Both" "NoReplace" "Eval")
(sdedr:define-refinement-size "global" 2 2 2 1 1 1)
(sdedr:define-refinement-size "doping" 0.074 0.074 0.074 0.037 0.037 0.037)
(sdedr:define-refinement-function "doping" "DopingConcentration" "MaxTransDiff" 1)
(sdedr:define-multibox-size "optics" 0.0102 0.0102 0.0102 0.005 0.005 0.005 0.001 0.001 0.001)
(sdedr:define-multibox-size "optics" 0.025 0.025 0.025 0.012 0.012 0.012 0.005 0.005 0.005)
(sdedr:define-multibox-placement "optics" "optics" "optics")
(sdedr:define-multibox-placement "optics" "optics" "optics")
(sdegeo:define-2d-contact (find-face-id (position 0 5 5)) "nContact")
(sdegeo:define-2d-contact (find-face-id (position 0 1 3)) "pContact")
(sde:build-mesh "n@node@")
(sdeio:save-tdr-bnd "n@node@.tdr" "n@node@.bnd")