(sde:set-process-up-direction "+z")
(sdegeo:set-default-boolean "ABA")
(sdegeo:create-rectangle (position 0 0 0) (position 0.1 9.45 0) "SiO2" "subox")
(sdegeo:create-rectangle (position -0.2 0 0) (position -0.1 9.48 0) "Metal" "seed")
(sdegeo:create-rectangle (position -0.2 0 0) (position -0.1 9.56 0) "AlGaN" "buffer")
(sdegeo:create-rectangle (position -0.2 0 0) (position -0.1 9.55 0) "GaN" "channel")
(sdegeo:create-rectangle (position -0.2 0.9 0) (position -0.1 4.13 0) "Silver" "Con.Gate")
(sdegeo:create-rectangle (position -0.2 0 0) (position -0.1 9.72 0) "AlGaN" "barrier2")
(sdegeo:fillet-2d (find-vertex-id (position -0.2 4.13 0)) 0.08)
(sdegeo:fillet-2d (find-vertex-id (position -0.2 9.72 0)) 0.08)
(sdegeo:fillet-2d (find-vertex-id (position -0.1 4.2135 0)) 0.05)
(sdegeo:fillet-2d (find-vertex-id (position -0.1 9.7465 0)) 0.05)
(sdegeo:bool-unite (find-material-id "AlGaN"))
(sdegeo:bool-unite (find-material-id "GaN"))
(sdegeo:bool-unite (find-material-id "Silver"))
(sde:build-mesh "n@node@")
(sdeio:save-tdr-bnd "n@node@.tdr" "n@node@.bnd")
