(sdegeo:create-rectangle (position -10 -10 -10) (position 10 10 10) "SiO2" "R.Filler")
(sdegeo:create-rectangle (position -10 -10 -10) (position 10 10 10) "Silicon" "IntSilicon")
(sdegeo:create-rectangle (position -10 -10 -10) (position 10 10 10) "SiO2" "R.SourceLine")
(sdegeo:create-rectangle (position -10 -10 -10) (position 10 10 10) "SiO2" "R.BitLine")
(sdegeo:create-rectangle (position -10 -10 -10) (position 10 10 10) "SiO2" "TunnelOxide")
(sdegeo:create-rectangle (position -10 -10 -10) (position 10 10 10) "Si3N4" "CTN")
(sdegeo:delete-region (find-material-id "XXX"))
(sdedr:define-refinement-window "W.Global" "Cuboid" (position -10 -10 -10) (position 10 10 10))
(sdedr:define-constant-profile "C.BF" "BoronActiveConcentration" 1e+15)
(sdedr:define-constant-profile "C.PP" "PhosphorusActiveConcentration" 9.7e+19)
(sdedr:define-constant-profile "C.BD" "BoronActiveConcentration" 1e+08)
(sdedr:define-constant-profile "C.PP" "PhosphorusActiveConcentration" 1e+08)
(sdedr:define-constant-profile-material "i_dop" "C.BF" "Silicon")
(sdedr:define-constant-profile-placement "P.Global" "C.BF" "W.Global")
(sdedr:define-refinement-size "R.Global" ['/', ['-', ['/', 'P.Gi', 40.0], ['/', 'P.Gi', 40.0]], ['/', ['-', ['/', 'P.Gi', 40.0], ['/', 'P.Gi', 40.0]], ['/', 'P.Gi', 40.0]] 0.0001 0.0001 0.0001]
(sdedr:define-refinement-size "R.Channel" @<@lwl@/40>@ @min@ @min@ 0.0001 0.0001 0.0001)
(sdedr:define-refinement-material "R.Channel" "R.Channel" "Silicon" )
(sdedr:define-refinement-placement "P.Global" "R.Global" "W.Global")
(sdegeo:set-contact (find-face-id (position 0 0 0)) "R.SSL")
(sdegeo:set-contact (find-face-id (position 0 -10 0)) "R.DSL")
(sdegeo:set-contact-boundary-faces (find-material-id "XXX") "R.SSL" "R.DSL")
(sdegeo:define-2d-contact (find-edge-id (position 0 0 @<@lwl@/2>@)) "R.SSL" "R.DSL")
(sde:build-mesh "n@node@")
(sdeio:save-tdr-bnd "n@node@.tdr" "n@node@.bnd")